### ISSUE TITLE
[request] Add a Operator Mono version

### ISSUE THREAD

**Issue by svictoreq** [Pustur/calamity-vscode#1]
An Operator Mono would make this theme even better.

**Comment by Pustur** [comment]
You can easily set the font that you want by using the `"editor.fontFamily"` property.
I personally use [Inconsolata](https://fonts.google.com/specimen/Inconsolata). 

I'm closing this since it's not really the theme's job to set the font, I'll leave this choice to the users.

**Comment by svictoreq** [comment]
Sorry if I was not specific enough... I was referring to creating an additional theme that would take full advantage of the italics on the Operaror Mono typeface. 

Here's an example, look:

![screenshot 01](https://user-images.githubusercontent.com/29575744/29908182-1ea3223e-8dee-11e7-942f-6835be29cf97.png)

![screenshot 02](https://user-images.githubusercontent.com/29575744/29908238-5d391a76-8dee-11e7-9442-53962c706ecc.png)


So I thought that it'd make the theme better...

**Comment by Pustur** [comment]
Oh now I see what you meant.

Would you be interested in implementing this? You are free to fork the project and do whatever you prefer with it.

**Comment by svictoreq** [comment]
I'm starting in coding, so I am not yet familiar with Git and GitHub, but when I am, I will create a repository and generate a PR. Thanks for the support.

**Comment by Pustur** [comment]
I'm going to close this issue since it's been open without activity for almost a year.

If you want to discuss this further you can always re-open this or submit a PR.
